# Configuration file for deep learning model
# ------------------------------
# Data parameters
model:
   name : 'cnn'
   input_dim: [28, 28, 1]
   output_dim: 10

data:
  dataset_path : 'data/processed/'
  image_dimension: [28, 28, 1]
  label_dimension : 1


# Training parameters
training:
  batch_size: 128
  num_epochs: 15
  output_path  : 'models'

# Logging and output parameters
mlflow:
  mlruns_path: 'models'
  tracking_uri: 'http://localhost:8080'
  experiment_name: 'cnn'
  tags :
    v1.2 : 'CNN based model for MNIST data'

# Grid search:
hyperparameter_tuning:
  batch_size: [128, 256]
  num_epochs: [10, 15, 20]